SELECT DISTINCT category
FROM Gold_Bara_Project.dim_products;

-- ## Data Exploration Step
USE information_schema;
SELECT * from information_schema.COLUMNS
WHERE TABLE_NAME = 'dim_customer';

-- ## Dimension Exploration Step ##
-- Explore how many countries we have customers from.
SELECT DISTINCT country FROM dim_customer;

-- Explore how many categories we have.
SELECT DISTINCT category,sub_category, product_name FROM dim_products order by 1,2,3;

-- ## Date Exploration Step
-- Find the first and last order_date
SELECT 
MIN(order_date) as first_ord_dt,
MAX(order_date) as last_ord_dt
FROM fact_sales;

-- How many years of sales are available
SELECT 
MIN(order_date) as first_ord_dt,
MAX(order_date) as last_ord_dt,
TIMESTAMPDIFF(YEAR, MIN(order_date), MAX(order_date)) AS total_sales_years
FROM fact_sales;

-- Find the age range like identify the yougest and oldest one
SELECT MIN(birth_date) as oldest_customer, MAX(birth_date) as yougest_customer,
TIMESTAMPDIFF(YEAR,MIN(birth_date),NOW()) as highest_age,
TIMESTAMPDIFF(YEAR,MAX(birth_date),NOW()) as lowest_age
FROM dim_customer;

-- ## Measure Exploration Step ##
-- 1. Find the Total Sales
SELECT SUM(sales_amount) as total_sales FROM fact_sales;

-- 2. Find how many items are sold
SELECT SUM(quantity) as total_quantity FROM fact_sales;

-- 3. Find the avg selling price
SELECT AVG(price) as avg_price FROM fact_sales;

-- 4. Find the total number of orders
SELECT COUNT(order_number) as total_order,
COUNT(DISTINCT(order_number)) as total_distinct_order FROM fact_sales;

-- 5. Find the total number of custormer
SELECT COUNT(DISTINCT(customer_id)) as total_customer FROM dim_customer;

-- 6. Find the total number of products
SELECT COUNT(DISTINCT(product_id)) as total_customer FROM dim_products;

-- 7. Find the total number of customers who place an order
SELECT COUNT(DISTINCT(customer_key)) as total_customer FROM fact_sales;

-- Generate a report that show all key metrics of the business 
SELECT 'Total Sales' as measure_name, SUM(sales_amount) as measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM(quantity) as measure_value FROM fact_sales
UNION ALL
SELECT 'Total No. Order' as measure_name, COUNT(DISTINCT(order_number)) as measure_value FROM fact_sales
UNION ALL
SELECT 'Average Price' as measure_name, ROUND(AVG(price)) as measure_value FROM fact_sales
UNION ALL
SELECT 'Total No. Product' as measure_name, COUNT(DISTINCT(product_id)) as measure_value FROM dim_products
UNION ALL
SELECT 'Total No. Customer' as measure_name, COUNT(DISTINCT(customer_key)) as measure_value FROM dim_customer;

-- ## Magnitude Exploration Step
-- Find total customer by country
SELECT country,
COUNT(customer_id) as total_customer
FROM dim_customer
GROUP BY country
ORDER By total_customer DESC;

-- Find total customer by gender
SELECT gender,
COUNT(customer_id) as total_customer
FROM dim_customer
GROUP BY gender
ORDER By total_customer DESC;

-- Find the total product by category
SELECT category,
COUNT(product_key) as total_product
FROM dim_products
GROUP BY category
ORDER BY total_product DESC;

-- What is the average cost of each category
SELECT category,
ROUND(AVG(cost)) as avg_cost
FROM dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated for each category
SELECT SUM(fs.sales_amount) as total_revenue,
dm.category as category
FROM fact_sales fs
LEFT JOIN dim_products dm
ON fs.product_key = dm.product_key
GROUP BY category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer
SELECT 
cm.first_name, cm.last_name,cm.country,
SUM(fs.sales_amount) as total_revenue
FROM fact_sales fs
LEFT JOIN dim_customer cm
ON fs.customer_key = cm.customer_key
GROUP BY cm.first_name,
		 cm.last_name,
		 cm.country
ORDER BY total_revenue DESC;

-- What is the distribution of sold items by each country
SELECT 
c.country,
COUNT(fs.quantity) as total_distribution
FROM fact_sales as fs
LEFT JOIN dim_customer c
ON fs.customer_key = c.customer_key
GROUP BY c.country
ORDER By total_distribution DESC;

-- ## Ranking Analysis ##
-- Which Top 5 product generate the highest revenue?
SELECT
SUM(fs.sales_amount) as total_revenue,
dm.product_name
FROM fact_sales fs
LEFT JOIN dim_products dm
ON fs.product_key = dm.product_key
GROUP BY dm.product_name
ORDER BY total_revenue DESC
LIMIT 5;

-- Which 5 worst product generate in revenue?
SELECT
SUM(fs.sales_amount) as total_revenue,
dm.product_name
FROM fact_sales fs
LEFT JOIN dim_products dm
ON fs.product_key = dm.product_key
GROUP BY dm.product_name
ORDER BY total_revenue ASC
LIMIT 5;

-- Find the top 10 customer who has generated highest revenue
SELECT 
cm.first_name, cm.last_name,cm.country,
SUM(fs.sales_amount) as total_revenue
FROM fact_sales fs
LEFT JOIN dim_customer cm
ON fs.customer_key = cm.customer_key
GROUP BY cm.first_name,
		 cm.last_name,
		 cm.country
ORDER BY total_revenue DESC
LIMIT 10;









